Get http://localhost:3005/api/getAll

### fetching details of the person

Get http://localhost:3005/api/6502136a39c46e08198f27bc

### add a new person

Post http://localhost:3005/api/
Content-Type: application/json

{
    "name":"Mark Essien",
    "age":35
}

#### modify details of an existing person

PATCH http://localhost:3005/api/6502136a39c46e08198f27bc
Content-Type: application/json

{
    "name":"James Doe"

}

### remove the person
DELETE  http://localhost:3005/api/6502136a39c46e08198f27bc